### ISSUE TITLE
threshold 1

### ISSUE THREAD

**Issue by AlexChien** [itering/subscan-multisig-ui#1]
When I input 1 in the threshold field, trying to create a 1/2 Multisig wallet.  The interface says 1 is an invalid number.

**Comment by carlhong** [comment]
We limit threshold between 2 and the number of members, same as polkadot apps

**Comment by AlexChien** [comment]
This is debatable I think.  In some scenarios, 1/m is required.  It means either member of the group or either one device of the list can represent others.  What do you think? @HackFisher

**Comment by carlhong** [comment]
@AlexChien  https://polkadot.js.org/docs/substrate/errors/#minimumthreshold  Threshold must be 2 or greater.

**Comment by AlexChien** [comment]
OK, understood.
