### ISSUE TITLE
交易确认页面增加交易详情

### ISSUE THREAD

**Issue by yakio** [itering/subscan-multisig-ui#12]
![image](https://user-images.githubusercontent.com/46353690/120453062-49db1400-c3c5-11eb-8400-dcb735785b13.png)
内容包含：
（1）extrinsic类型：module（call）+docs注释
（2）parameter

**Comment by sxlwar** [comment]
![image](https://user-images.githubusercontent.com/20088392/121141004-16890100-c86d-11eb-9904-76f9fed1cb9a.png)
