### ISSUE TITLE
升级各个网络的 type.json

### ISSUE THREAD

**Issue by yakio** [itering/subscan-multisig-ui#13]

**Comment by yakio** [comment]
![image](https://user-images.githubusercontent.com/46353690/120465364-79dbe480-c3d0-11eb-8fbc-d10e2015b0f6.png)

![image](https://user-images.githubusercontent.com/46353690/120465399-852f1000-c3d0-11eb-8f7f-2a76757d8979.png)

**Comment by sxlwar** [comment]
seems like fixed in pr #16
 
![image](https://user-images.githubusercontent.com/20088392/120972916-d9efd380-c7a0-11eb-8088-7b2ada1844e3.png)

![image](https://user-images.githubusercontent.com/20088392/120973041-00ae0a00-c7a1-11eb-9128-8e848a6c25d4.png)
