### ISSUE TITLE
Newly created wallet not found on subscan

### ISSUE THREAD

**Issue by AlexChien** [itering/subscan-multisig-ui#2]
When a new multi-sig wallet is created, it's not found on Subscan.  Guess it's not actually created on the chain (correct me if I am wrong).  Until some other address sends some tokens to this address or maybe some other activities, it's "picked up" by Subscan.

In the UI, there should be some note explaining this, otherwise, the creator might misunderstand that the multi-sig wallet creation is failed.

**Comment by wuminzhe** [comment]
yes, only when this multi-sig wallet has an extrinsic issued, it will be on chain

**Comment by AlexChien** [comment]
We need some way to inform the user about this 'cause it will cause confusion and a sense of un-safety.  Some _i_ icon next to Subscan link?  "Newly created wallet will not be shown on the Subscan, until first extrinsic is confirmed", something like that?
