### ISSUE TITLE
Clicking on View on Subscan does nothing

### ISSUE THREAD

**Issue by nblogist** [itering/subscan-multisig-ui#7]
When I click the "View on Subscan" it doesn't take me to subscan
![image](https://user-images.githubusercontent.com/35498810/103037438-a7a13f80-458d-11eb-9428-079313c9ed7f.png)

**Comment by carlhong** [comment]
fixed in https://github.com/itering/subscan-multisig-ui/commit/1e144f3dcbc89a3557adb5d31aeab666608a058f
